/// Represents hyper-local atmospheric weather data retrieved from
/// OpenWeatherMap or generated by the microclimate simulation engine.
class WeatherData {
  final double temperatureC;
  final double relativeHumidityPct;
  final double atmosphericPressureHpa;
  final double uvIndex;
  final double windSpeedMps;
  final String weatherCondition;
  final String weatherDescription;
  final String iconCode;
  final String cityName;
  final String countryCode;
  final double latitude;
  final double longitude;
  final DateTime sunriseTime;
  final DateTime sunsetTime;
  final DateTime recordedAt;

  const WeatherData({
    required this.temperatureC,
    required this.relativeHumidityPct,
    required this.atmosphericPressureHpa,
    required this.uvIndex,
    required this.windSpeedMps,
    required this.weatherCondition,
    required this.weatherDescription,
    required this.iconCode,
    required this.cityName,
    required this.countryCode,
    required this.latitude,
    required this.longitude,
    required this.sunriseTime,
    required this.sunsetTime,
    required this.recordedAt,
  });

  /// Factory constructor to parse OpenWeatherMap 2.5 current weather JSON payload.
  factory WeatherData.fromOpenWeatherMapJson(Map<String, dynamic> json) {
    final main = json['main'] as Map<String, dynamic>? ?? {};
    final weatherList = json['weather'] as List<dynamic>? ?? [];
    final firstWeather = weatherList.isNotEmpty
        ? weatherList[0] as Map<String, dynamic>
        : <String, dynamic>{};
    final sys = json['sys'] as Map<String, dynamic>? ?? {};
    final wind = json['wind'] as Map<String, dynamic>? ?? {};
    final coord = json['coord'] as Map<String, dynamic>? ?? {};

    final sunriseSec = sys['sunrise'] as int? ?? 0;
    final sunsetSec = sys['sunset'] as int? ?? 0;
    final dtSec = json['dt'] as int? ?? (DateTime.now().millisecondsSinceEpoch ~/ 1000);

    return WeatherData(
      temperatureC: (main['temp'] as num?)?.toDouble() ?? 28.0,
      relativeHumidityPct: (main['humidity'] as num?)?.toDouble() ?? 75.0,
      atmosphericPressureHpa: (main['pressure'] as num?)?.toDouble() ?? 1012.0,
      uvIndex: (json['uvi'] as num?)?.toDouble() ?? 5.0,
      windSpeedMps: (wind['speed'] as num?)?.toDouble() ?? 2.5,
      weatherCondition: firstWeather['main'] as String? ?? 'Clear',
      weatherDescription: firstWeather['description'] as String? ?? 'clear sky',
      iconCode: firstWeather['icon'] as String? ?? '01d',
      cityName: json['name'] as String? ?? 'Colombo',
      countryCode: sys['country'] as String? ?? 'LK',
      latitude: (coord['lat'] as num?)?.toDouble() ?? 6.9271,
      longitude: (coord['lon'] as num?)?.toDouble() ?? 79.8612,
      sunriseTime: sunriseSec > 0
          ? DateTime.fromMillisecondsSinceEpoch(sunriseSec * 1000)
          : DateTime.now().copyWith(hour: 6, minute: 0),
      sunsetTime: sunsetSec > 0
          ? DateTime.fromMillisecondsSinceEpoch(sunsetSec * 1000)
          : DateTime.now().copyWith(hour: 18, minute: 15),
      recordedAt: DateTime.fromMillisecondsSinceEpoch(dtSec * 1000),
    );
  }

  /// Converts model to Map for serialization or debugging.
  Map<String, dynamic> toJson() {
    return {
      'temperatureC': temperatureC,
      'relativeHumidityPct': relativeHumidityPct,
      'atmosphericPressureHpa': atmosphericPressureHpa,
      'uvIndex': uvIndex,
      'windSpeedMps': windSpeedMps,
      'weatherCondition': weatherCondition,
      'weatherDescription': weatherDescription,
      'iconCode': iconCode,
      'cityName': cityName,
      'countryCode': countryCode,
      'latitude': latitude,
      'longitude': longitude,
      'sunriseTime': sunriseTime.toIso8601String(),
      'sunsetTime': sunsetTime.toIso8601String(),
      'recordedAt': recordedAt.toIso8601String(),
    };
  }

  /// Default mock instance centered on tropical indoor environment (Colombo, Sri Lanka).
  factory WeatherData.mockTropicalDefault() {
    final now = DateTime.now();
    return WeatherData(
      temperatureC: 29.5,
      relativeHumidityPct: 78.0,
      atmosphericPressureHpa: 1011.0,
      uvIndex: 6.2,
      windSpeedMps: 3.2,
      weatherCondition: 'Clouds',
      weatherDescription: 'scattered clouds',
      iconCode: '03d',
      cityName: 'Colombo',
      countryCode: 'LK',
      latitude: 6.9271,
      longitude: 79.8612,
      sunriseTime: DateTime(now.year, now.month, now.day, 6, 4),
      sunsetTime: DateTime(now.year, now.month, now.day, 18, 14),
      recordedAt: now,
    );
  }
}
